### ISSUE TITLE
🐛 BUG: Card icons have shape problem on hover.

### ISSUE THREAD

**Issue by ih-abir** [Nomishka/Tailwind2#3]
**Describe the bug**
In section "We do awesome services for our clients" there are cards, when hovering on them the icon looks square in shape. but it will be look like round & add some shadow under of it.

**Screenshot**

![image](https://github.com/Nomishka/Tailwind2/assets/71958321/64e4d295-304d-415b-b03f-13fbec12e417)

**Steps to Reproduce**

1. Go to [https://nomishka.github.io/Tailwind2/)
2. Scroll down to "We do awesome services for our clients" section

**Expected behavior**
The card icons should be round on hover and should have some shadow.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Comment by Nomishka** [comment]
Closed the issue with the pull request "Bugfix/We do awesome services for our clients" #4
